# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hptrivia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='book_number',
            field=models.IntegerField(choices=[(1, "Harry Potter and the Philosopher's Stone"), (2, 'Harry Potter and the Chamber of Secrets'), (3, 'Harry Potter and the Prisoner of Azkaban'), (4, 'Harry Potter and the Goblet of Fire'), (5, 'Harry Potter and the Order of the Phoenix'), (6, 'Harry Potter and the Half-Blood Prince'), (7, 'Harry Potter and the Deathly Hallows')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified_datetime',
            field=models.DateTimeField(null=True, verbose_name='date modified'),
        ),
    ]
